smok test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -116,4 +116,15 @@ jobs:
             ${{ secrets.DOCKER_HUB_USERNAME }}/petclinic:${{ env.TIMESTAMP }}
             ${{ secrets.DOCKER_HUB_USERNAME }}/petclinic:${{ env.SHORT_SHA }}
             ${{ secrets.DOCKER_HUB_USERNAME }}/petclinic:latest
-  
+            
+      - name: Smoke test Render app
+        run : |
+          for i in $(seq 1 3); do
+            curl --fail https://petclinic.onrender.com && exit 0
+            echo "Attempt $i failed. Retrying in 10 seconds..."
+            if [ "$i" -eq 3 ]; then
+              echo "❌ Smoke test failed after 3 attempts."
+            fi
+            sleep 10
+          done
+          exit 1
